version: '3'
services:
  frontend:
    container_name: gestionate
    build:
      context: ./
      dockerfile: dev.dockerfile
    volumes:
      - "./gestionate:/app"
    ports:
      - "4200:4200"
      - "49153:49153"
    command: /bin/sh
    stdin_open: true
    tty: true
